---
# tasks file for gschaetz.provision-desktop
- include_vars:
    file: "{{ application_setup }}"
    name: apps

# delete desktop entries
- name: Creates main directory
  shell: "rm -rf {{ local_home }}/Desktop/*.desktop"

# create main directory
- name: Creates main directory
  file: path={{ desktop_dir }} state=directory

# create directories for applications
- name: Creates application directories
  file: path={{ desktop_dir }}{{ item.key }} state=directory
  with_dict: "{{ apps.applications }}"

# download app icons
- name: Download app icons
  get_url:
    url: "{{ item.value.desktop_icon_download_url }}"
    dest: "{{ desktop_dir }}{{ item.key }}/{{ item.value.desktop_icon }}"
    mode: 0440
  with_dict: "{{ apps.applications }}"

# create desktop icon 
- template:
    src: "{{ local_home }}/ansible/templates/gnome-desktop-template.j2"
    dest: "{{ local_home }}/Desktop/{{ item.value.desktop_name }}.desktop"
    mode: 0777
  with_dict: "{{ apps.applications }}"

# create docker files 
- template:
    src: "{{ local_home }}/ansible/templates/app-start-docker.j2"
    dest: "{{ desktop_dir }}{{ item.key }}/start.sh"
    mode: 0777
  with_dict: "{{ apps.applications }}"



# copy 


# create 


# implementaton_type: 'docker',
#        file_location: '/home/vagrant/devdesktop/',
#        docker_repository: 'registry.hub.docker.io',
#        docker_repository_username: 'test',
#        docker_repository_password: 'test',
#        docker_image: 'tramasoli/firefox-image:latest',
#        docker_ports: '22:22,443:443',
#        docker_volumes: '/home/vagrant/devdestkop/nexus3/:/test',
#       desktop_type: 'gnome',
#        desktop_name: 'Nexus 3 Latest',
#        desktop_exec: '/home/vagrant/devdesktop/nexus3/start.sh',
#        desktop_icon: 'http://iosicongallery.com/img/512/firefox-web-browser-2015.png',
#        gui_app: true