---
- include_vars:
    file: "{{ gnomeSettings }}"
    name: settings

- name: install shell-extension dashtodock
  apt:
    name: gnome-shell-extension-dashtodock
    state: present
  become: true

- name: move extension to gsetting locations
  shell: cp /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml /usr/share/glib-2.0/schemas/ && glib-compile-schemas /usr/share/glib-2.0/schemas/
  become: true

- name: set gnome settings
  shell: gsettings set {{ item.value.setting }}
  with_dict: '{{ settings.gnome }}'

- name: download background image
  get_url:
    url: "{{ item.value.background_url }}"
    dest: "{{ desktop_dir }}/resources/background.jpg"
    mode: 0440
  with_dict: '{{ settings.gnome_background }}'

- name: set background image
  shell: gsettings set org.gnome.desktop.background picture-uri file:///{{ desktop_dir }}/resources/background.jpg    
  
