---
- hosts: all
  vars:
    current_path: "{{ lookup('env','PWD') }}"

    local_home: "{{ lookup('env','HOME') }}"
    project_home: "{{ DESKTOP_PROJECT_DIR | default(current_path) }}"

    gnome_settings_yaml: "{{ project_home }}/desktop-ansible-settings/gnome-settings.yml"     
    applications_yaml:  "{{ project_home }}/desktop-ansible-settings/applications.yml"
    packages_yaml: "{{ project_home }}/desktop-ansible-settings/packages.yml"

    desktop_directory: "{{ local_home }}/.desktop/"

  roles:
    # - { role: gschaetz.packages, 
    #     packages: "{{ packages_yaml }}"
    #   }
    # - { role: gschaetz.install-docker,
    #     non_root_user: 'vagrant'
    #   }
    - { role: gschaetz.provision-desktop,
        application_setup: "{{ applications_yaml }}",
        desktop_dir: "{{ desktop_directory }}"
      }
    - { role: gschaetz.desktopsetup, 
        gnomeSettings: "{{ gnome_settings_yaml }}"
      }
