---
- hosts: all
  vars:
    packages_list_json: "{{lookup('file','/home/vagrant/ansible/desktop-ansible-settings/packages.json')}}"
    gnome_settings_json: "{{lookup('file','/home/vagrant/ansible/desktop-ansible-settings/gnome-settings.json')}}"  
  tasks:
    - apt: name={{ item }} state=present
      with_items: "{{ packages_list_json }}"  
      become: true
#  roles:
#    - { role: gschaetz.desktopsetup, 
#        gnomeSettings: "{{ gnome_settings_json }}"
#      }
#    - { role: gschaetz.install-docker,
#        non_root_user: 'vagrant'
#      }
#    - { role: gschaetz.provision-desktop,
#        implementaton_type: 'docker',
#        file_location: '/home/vagrant/devdesktop/',
#        docker_repository: 'registry.hub.docker.io',
#        docker_repository_username: 'test',
#        docker_repository_password: 'test',
#        docker_image: 'tramasoli/firefox-image:latest',
#        docker_ports: '22:22,443:443',
#        docker_volumes: '/home/vagrant/devdestkop/nexus3/:/test',
#        desktop_type: 'gnome',
#        desktop_name: 'Nexus 3 Latest',
#        desktop_exec: '/home/vagrant/devdesktop/nexus3/start.sh',
#        desktop_icon: 'http://iosicongallery.com/img/512/firefox-web-browser-2015.png',
#        gui_app: true
#      }