---
applications:
    firefox:
        implementation_type: docker
        docker_image: jess/firefox:latest
        docker_ports: 
        docker_volumes: -v /:/host_drive
        show_on_desktop: false
        desktop_name: Firefox
        desktop_exec: firefox
        desktop_icon_download_url: https://findicons.com/files/icons/1070/software/128/mozilla_firefox.png
        desktop_icon: firefox.png
        menu_category: Network;WebBrowser;
        gui_app: true
        extra_docker_flags: 
        docker_network: dev
        app_persistent_dir:
    chrome:
        implementation_type: docker
        docker_image: jess/chrome:latest
        docker_ports: 
        docker_volumes: -v /:/host_drive
        show_on_desktop: true
        desktop_name: Chrome
        desktop_exec: chrome
        desktop_icon_download_url: http://icons.iconarchive.com/icons/google/chrome/128/Google-Chrome-icon.png
        desktop_icon: chrome.png
        menu_category: Network;WebBrowser;
        gui_app: true
        extra_docker_flags: --privileged
        docker_network: dev
        app_persistent_dir:
    wordpress_compose:
        implementation_type: docker_compose
        show_on_desktop: true
        desktop_name: wordpress_compose
        desktop_exec: wordpress_compose
        desktop_icon_download_url: http://icons.iconarchive.com/icons/graphics-vibe/simple-rounded-social/128/wordpress-icon.png
        desktop_icon: wordpress_compose.png
        menu_category: Network;WebBrowser;
        gui_app: true
        compose_version: "version: '2'"
        compose_network: dev
        compose_definition:
            services:
                db:
                    image: mysql:5.7
                    volumes:
                        - dbdata:/var/lib/mysql
                    restart: always
                    environment:
                        MYSQL_ROOT_PASSWORD: somewordpress
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
                wordpress:
                    depends_on:
                        - db
                    image: wordpress:latest
                    ports:
                        - "8000:80"
                    restart: always
                    environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
            volumes:
                dbdata: