---
applications:
    firefox:
        implementation_type: docker
        docker_image: gschaetz/firefox:latest
        docker_ports: 
        docker_volumes: -v /:/host_drive -v /dev/shm:/dev/shm
        show_on_desktop: false
        desktop_name: Firefox
        desktop_exec: firefox
        desktop_icon_download_url: https://findicons.com/files/icons/1070/software/128/mozilla_firefox.png
        desktop_icon: firefox.png
        menu_category: Network;WebBrowser;
        gui_app: true
        pulse_audio: true
        extra_docker_flags: --cpus 2 --device /dev/dri
        docker_network: host
        docker_sec_comp: false
        app_persistent_dir: /home/user
        app_persistent_download_dir: /home/user/Downloads
        docker_entrypoint: 
    wargames:
        implementation_type: docker
        docker_image: gschaetz/wargames:latest
        docker_ports: 
        docker_volumes: 
        show_on_desktop: false
        desktop_name: War Games
        desktop_exec: wargames
        desktop_icon_download_url: https://cdn.iconscout.com/icon/free/png-256/wargaming-1-283119.png
        desktop_icon: wargames.png
        menu_category: Network;Game;
        gui_app: false
        pulse_audio: false
        extra_docker_flags: 
        docker_network: host
        docker_sec_comp: false
        app_persistent_dir: 
        app_persistent_download_dir: 
        docker_entrypoint: 
    chrome:
        implementation_type: docker
        docker_image: gschaetz/chrome:latest
        docker_ports: 
        docker_volumes: -v /:/host_drive -v /dev/shm:/dev/shm
        show_on_desktop: false
        desktop_name: Chrome
        desktop_exec: chrome
        desktop_icon_download_url: http://icons.iconarchive.com/icons/google/chrome/128/Google-Chrome-icon.png
        desktop_icon: chrome.png
        menu_category: Network;WebBrowser;
        gui_app: true
        pulse_audio: false
        extra_docker_flags: --cpus 1 --memory 1024mb --device /dev/dri 
        docker_network: host
        docker_sec_comp: true
        docker_sec_comp_download_url: https://raw.githubusercontent.com/jfrazelle/dotfiles/master/etc/docker/seccomp/chrome.json
        app_persistent_dir: /data
        app_persistent_download_dir: /home/chrome/Downloads/
        docker_entrypoint: 
    vscode:
        implementation_type: docker
        docker_image: gschaetz/vscode:latest
        docker_ports:
        docker_volumes: -v /:/host_drive -v /var/run/docker.sock:/var/run/docker.sock
        show_on_desktop: false
        desktop_name: VScode 
        desktop_exec: vscode
        desktop_icon_download_url: https://upload.wikimedia.org/wikipedia/commons/f/f3/Visual_Studio_Code_0.10.1_icon.png
        desktop_icon: vscode.png
        menu_category: Development;IDE;
        gui_app: true
        pulse_audio: false
        extra_docker_flags: --cpus 1 --memory 1024mb 
        docker_network: host
        docker_sec_comp: false
        app_persistent_dir: /home/user/
        app_persistent_download_dir:
        docker_entrypoint: 
    wordpress_compose:
        implementation_type: docker_compose
        show_on_desktop: true
        desktop_name: wordpress_compose
        desktop_exec: wordpress_compose
        desktop_icon_download_url: http://icons.iconarchive.com/icons/graphics-vibe/simple-rounded-social/128/wordpress-icon.png
        desktop_icon: wordpress_compose.png
        menu_category: Network;WebBrowser;
        gui_app: true
        pulse_audio: false
        compose_version: "version: '2'"
        compose_network: dev
        compose_definition:
            services:
                db:
                    image: mysql:5.7
                    volumes:
                        - dbdata:/var/lib/mysql
                    restart: always
                    environment:
                        MYSQL_ROOT_PASSWORD: somewordpress
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
                wordpress:
                    depends_on:
                        - db
                    image: wordpress:latest
                    ports:
                        - "8000:80"
                    restart: always
                    environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
            volumes:
                dbdata: